apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: httpbin
spec:
  parentRefs:
    - name: httpbin-gateway
  # hostnames:
  #   - httpbin.example.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /status
        - path:
            type: PathPrefix
            value: /delay
        - path:
            type: PathPrefix
            value: /headers
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: My-Custom-Header
                value: qwerty
      backendRefs:
        - name: httpbin
          port: 8000
