apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  ingressClassName: istio
  rules:
    - http:
        paths:
          - path: /delay
            pathType: Prefix
            backend:
              service:
                name: httpbin
                port:
                  number: 8000
