apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../components/aks-gateway-fix
resources:
  - https://raw.githubusercontent.com/istio/istio/release-1.19/samples/httpbin/httpbin.yaml
  - httpbin-gateway.gateway.yaml
  - httpbin.http-route.yaml
  # - istio.ingress-class.yaml
  # - httpbin.ingress.yaml # BUG: doesn't work

# kubectl diff -k .
# kubectl apply -k .

# curl -s -I -H Host:httpbin.example.com http://20.171.201.120/status/200
# curl -s -I -H Host:httpbin.example.com http://20.171.201.120/delay/1
# curl -s -I -H Host:httpbin.example.com http://20.14.26.201/delay/1
