apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress
spec:
  selector:
    matchLabels:
      istio.io/gateway-name: bookinfo-gateway
  action: ALLOW
  rules:
    - to:
        - operation:
            methods:
              - GET
