apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../00-common/bookinfo
  - ratings.virtual-service.yaml
  - reviews.virtual-service.yaml

# kubectl diff -k .
# kubectl apply -k .

# http://20.150.154.102/productpage
