apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/istio/istio/release-1.19/samples/tcp-echo/tcp-echo.yaml
  - https://raw.githubusercontent.com/istio/istio/release-1.19/samples/sleep/sleep.yaml
  - allow-tcp-echo.authorization-policy.yaml

# kubectl kustomize . > output.yaml
# kubectl diff -k .
# kubectl apply -k .
# kubectl delete -k .

# SLEEP=`kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name}`

# kubectl exec $SLEEP -c sleep -- sh -c 'echo "port 9000" | nc tcp-echo 9000'
# "hello port 9000"

# kubectl exec $SLEEP -c sleep -- sh -c 'echo "port 9001" | nc tcp-echo 9001'
# ""
