apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../00-common/bookinfo
  - reviews.http-route.yaml

# kubectl kustomize . > output.yaml
# kubectl diff -k .
# kubectl apply -k .
# kubectl delete -k .

# http://20.14.21.134/productpage
