apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: httpbin-deny
spec:
  selector:
    matchLabels:
      istio.io/gateway-name: httpbin-gateway
  action: DENY
  rules:
    - to:
        - operation:
            ports:
              - "80"
            methods:
              - POST
