apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../components/aks-gateway-fix
resources:
  - https://raw.githubusercontent.com/istio/istio/release-1.19/samples/httpbin/httpbin.yaml
  - https://raw.githubusercontent.com/istio/istio/release-1.19/samples/httpbin/gateway-api/httpbin-gateway.yaml
  - request-authentication.yaml
  - deny.authorization-policy.yaml # deny POST
  - allow.authorization-policy.yaml # allow authorized and iss=testing@secure.istio.io and sub=testing@secure.istio.io and "groups" has "group1"
  # - virtual-service.yaml # not supported by Gateway API

# kubectl kustomize . > output.yaml
# kubectl diff -k .
# kubectl apply -k .
# kubectl delete -k .

# curl -i 20.14.44.26/headers
# 403 Forbidden

# curl -iH "Authorization: Bearer deadbeef" 20.14.44.26/headers
# 401 Unauthorized

# TOKEN=`curl https://raw.githubusercontent.com/istio/istio/release-1.19/security/tools/jwt/samples/demo.jwt -s`
# echo "$TOKEN" | cut -d '.' -f2 - | base64 --decode
# curl -iH "Authorization: Bearer $TOKEN" 20.14.44.26/headers
# 403 Forbidden

# TOKEN_GROUP=`curl https://raw.githubusercontent.com/istio/istio/release-1.19/security/tools/jwt/samples/groups-scope.jwt -s`
# echo "$TOKEN_GROUP" | cut -d '.' -f2 - | base64 --decode
# curl -iH "Authorization: Bearer $TOKEN_GROUP" 20.14.44.26/headers
# 200 OK

# curl -iX POST 20.14.44.26/post
# 403 Forbidden

# curl -iH "Authorization: Bearer $TOKEN_GROUP" -X POST 20.14.44.26/post
# 403 Forbidden
