apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: jwt-example
spec:
  selector:
    matchLabels:
      istio.io/gateway-name: httpbin-gateway
  jwtRules:
    - issuer: testing@secure.istio.io
      jwksUri: https://raw.githubusercontent.com/istio/istio/release-1.19/security/tools/jwt/samples/jwks.json
      outputPayloadToHeader: x-jwt-token
      outputClaimToHeaders:
        - header: x-jwt-claim-exp
          claim: exp
        - header: x-jwt-claim-group
          claim: groups # BUG: arrays are not supported
