apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: reviews
spec:
  parentRefs:
    - group: ""
      kind: Service
      name: reviews
  rules:
    - matches:
        - headers:
            - name: end-user
              value: jason
      backendRefs:
        - name: reviews-v3
          port: 9080
    - backendRefs:
        - name: reviews-v1
          port: 9080
