apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
spec:
  hosts:
    - ratings
  http:
    - match:
        - headers:
            end-user:
              exact: jason
      fault:
        delay:
          percentage:
            value: 100.0
          fixedDelay: 2s
        # abort:
        #   percentage:
        #     value: 100.0
        #   httpStatus: 500
      route:
        - destination:
            host: ratings
    - route:
        - destination:
            host: ratings
