apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../00-common/bookinfo
  - filter-local-ratelimit-svc-1.envoy-filter.yaml
  # - filter-local-ratelimit-svc-2.envoy-filter.yaml

# kubectl kustomize . > output.yaml
# kubectl diff -k .
# kubectl apply -k .
# kubectl delete -k .
